name: felicitup
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  either_dart: ^1.0.0
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  intl: ^0.18.1
  intl_utils: ^2.8.7
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  phosphor_flutter: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    # - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 500

flutter_intl:
  enabled: true
  class_name: IntlTrans
  main_locale: es
  arb_dir: lib/l10n
  output_dir: lib/gen

flutter_gen:
  output: lib/gen
